FROM eclipse-temurin:24 AS builder

COPY . .

RUN ./gradlew clean bootJar --no-daemon

FROM openjdk:24-jdk-slim

RUN useradd -m appuser
USER appuser

COPY --from=builder ./build/libs/*.jar ./app.jar

EXPOSE 8080
CMD ["java", "-jar", "app.jar"]